---
variables:
  DOCKER_IMAGE_NAME: lansible/adguardhome

include:
  - template: Container-Scanning.gitlab-ci.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/master/default.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/master/docker-build.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/master/sast-cis-benchmark.yml

test_amd64:
  extends: .test
  variables:
    DOCKER_COMMAND: --version

test_arm64:
  extends: .test
  variables:
    DOCKER_COMMAND: --version
