---
apiVersion: v1
kind: Service
metadata:
  name: adguardhome
  labels:
    app: adguardhome
spec:
  selector:
    app: adguardhome
  ports:
    - nodePort: 31053
      port: 53
      name: dns
      targetPort: dns
    - nodePort: 31300
      port: 3000
      name: dash
      targetPort: dash
  type: NodePort
